### ISSUE TITLE
Fatal crash on high load

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/webircgateway#11]
Log output:
~~~
fatal error: concurrent map read and map write2017/06/08 12:26:33 L_DEBUG client:1438 clientLineWorker() client.Recv closed


goroutine 43587 [running]:
runtime.throw(0x8cb172, 0x21)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:596 +0x95 fp=0xc422ef0708 sp=0xc422ef06e8
runtime.mapaccess1_faststr(0x83bb20, 0xc4226c40c0, 0xc422eae7bb, 0x1, 0xc4200100a0)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/hashmap_fast.go:217 +0x4cf fp=0xc422ef0768 sp=0xc422ef0708
github.com/kiwiirc/webircgateway/pkg/webircgateway.kiwiircHandler.func1.1(0xc422123f80, 0xc4226c40c0, 0xc422eae7bb, 0x1)
        /Users/darren/go/src/github.com/kiwiirc/webircgateway/pkg/webircgateway/clientKiwiirc.go:124 +0x76 fp=0xc422ef07c0 sp=0xc422ef0768
runtime.goexit()
        /usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc422ef07c8 sp=0xc422ef07c0
created by github.com/kiwiirc/webircgateway/pkg/webircgateway.kiwiircHandler.func1
        /Users/darren/go/src/github.com/kiwiirc/webircgateway/pkg/webircgateway/clientKiwiirc.go:126 +0x54c
~~~

**Comment by prawnsalad** [comment]
fatal error: concurrent map iteration and map write
~~~
goroutine 6919 [running]:
runtime.throw(0x8cd37d, 0x26)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:596 +0x95 fp=0xc4217a9d68 sp=0xc4217a9d48
runtime.mapiternext(0xc4217a9f58)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/hashmap.go:737 +0x7ee fp=0xc4217a9e18 sp=0xc4217a9d68
github.com/kiwiirc/webircgateway/pkg/webircgateway.kiwiircHandler.func1(0xac0160, 0xc421044dc0, 0xc4204ec3f0)
        /Users/darren/go/src/github.com/kiwiirc/webircgateway/pkg/webircgateway/clientKiwiirc.go:146 +0x21a fp=0xc4217a9fc8 sp=0xc4217a9e18
runtime.goexit()
        /usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4217a9fd0 sp=0xc4217a9fc8
created by github.com/kiwiirc/webircgateway/pkg/webircgateway.kiwiircHandler
        /Users/darren/go/src/github.com/kiwiirc/webircgateway/pkg/webircgateway/clientKiwiirc.go:149 +0x7e
~~~

**Comment by prawnsalad** [comment]
Fixed in https://github.com/kiwiirc/webircgateway/commit/acd2c03fd45ca60993ca6c7f1877eec7df591aa0
